Add check for response type mapping before deserializing
pyansys/openapi-common pull request #312
Opened 2023-01-30 15:49 UTC by ludovicsteinbach

Closes #311 

This PR adds allows `response_type` to be a mapping.

2023-01-31 12:33 UTC, Andy-Grigg commented on src/ansys/openapi/common/_api_client.py
> +        response_type: Union[str, Dict[int, str], None] = None,
As discussed in https://github.com/pyansys/openapi-client-template/pull/82, I'd prefer having two separate kwargs here. This does mean that the two could conflict, but I think it's just something we'll have to document.

2023-02-01 12:08 UTC, Andy-Grigg requested changes
I actually just checked and saw the tests aren't passing. So withholding my approval until then!

2023-02-01 14:23 UTC, ludovicsteinbach commented
Tests are now passing on all platforms.

I've tested locally that grantami-bomanalytics tests (with mocked responses) pass with the wheel generated in the PR, i.e. it can handle client code generated with the old template, and I've also tested that client code generated with the new template (using response type map) also process responses correctly. All works as expected

2023-02-01 14:28 UTC, Andy-Grigg approved these changes

2023-02-01 14:49 UTC, ludovicsteinbach commented on src/ansys/openapi/common/_api_client.py
> +            _response_type: Optional[str]
In the first, it was indeed necessary for mypy. It might not be necessary anymore, I'll check and remove if possilbe

2023-02-02 10:17 UTC, da1910 approved these changes

2023-02-02 16:27 UTC, merged